<a href="https://colab.research.google.com/github/AJihwan/2024-intro-DA/blob/main/w04_1_python_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 01 패키지 numpy 개요와 자료형 ndnarra

## 다차원 배열 ndarray

In [ ]:
import numpy as np

a = np.ndarray(shape=(2,2),dtype=int)
a

array([[     97493324266562,                   0],
       [7306090318617649184, 8386106492501113458]])

## 내장함수 array()로 ndarray 생성

In [ ]:
import numpy as np

a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
import numpy as np

np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np.array(['가나다','라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
lang = np.array(['파이썬','자바','씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1,2.5,3))
b

array([1. , 2.5, 3. ])